default_language_version:
    python: python3

repos:
-   repo:  https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        args: ["--ignore-whitespace", "--settings-path", "./", "--recursive"]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: flake8
      additional_dependencies: ["flake8-string-format"]
    - id: trailing-whitespace
    - id: no-commit-to-branch
      args: [--branch, develop, --branch, master]
-   repo: https://github.com/schmir/ethlint-pre-commit.git
    rev: ceedc72aa232b9391840256c7781226a3e238b1a
    hooks:
    - id: ethlint
      args: ["--config", "contracts/.soliumrc.json"]
