version: 2.1

executors:
  ubuntu-builder:
    docker:
      - image: trustlines/builder:master23
        environment:
          - SOLC_VERSION=v0.5.8
    working_directory: ~/repo

# define some common commands
# see https://circleci.com/docs/2.0/configuration-reference/#commands-requires-version-21
commands:
  create-venv:
    description: "Create venv"
    steps:
      - run:
          name: Create python venv
          command: |
            python3 -m venv venv
            venv/bin/pip install -c constraints.txt pip wheel setuptools

  config-path:
    description: "set environment variables and change PATH"
    steps:
    - run:
        name: Configuring PATH
        command: |
          echo 'export PATH=~/bin:~/opt/node/bin:~/repo/venv/bin:${PATH}; . ~/.nvm/nvm.sh' >> ${BASH_ENV}

jobs:
  run-flake8:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Run flake8
          command: |
            flake8 merkle_drop tests

  run-black:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Run black
          command: |
            black --check merkle_drop tests

  run-solium:
    executor: ubuntu-builder
    steps:
      - checkout
      - config-path
      - run:
          name: Install ethlint (=solium)
          command: |
            npm install -g 'ethlint@>=1.0.9'
      - run:
          name: Run solium
          command: |
            cd contracts
            solium --dir contracts
  install:
    executor: ubuntu-builder
    steps:
      - checkout
      - config-path
      - restore_cache:
          key: venv-{{ checksum "constraints.txt" }}-{{ checksum "requirements.txt" }}
      - create-venv
      - run:
          name: Install codecov
          command: |
            pip install -c constraints.txt codecov
      - run:
          name: Install requirements
          command: |
            pip install -c constraints.txt -r requirements.txt
      - save_cache:
          key: venv-{{ checksum "constraints.txt" }}-{{ checksum "requirements.txt" }}
          paths:
            - venv
      - run:
          name: Install package
          command: |
            pip install -c constraints.txt -e .
      - run:
          name: Verify installed packages have compatible dependencies
          command: |
            pip check
      - persist_to_workspace:
          root: "~"
          paths:
            - repo

  run-pytest:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Create test-reports folder
          command: mkdir test-reports
      - run:
          name: Run pytest
          command: pytest --cov merkle_drop --junitxml=test-reports/junit.xml tests/
      - run:
          name: Upload coverage report
          command: codecov
      - store_test_results:
          path: test-reports

  run-mypy:
    executor: ubuntu-builder
    steps:
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Run mypy
          command: |
            mypy --ignore-missing-imports merkle_drop tests

workflows:
  version: 2
  default:
    jobs:
      #- run-solium
      - install
      - run-flake8:
          requires:
            - install
      - run-black:
          requires:
            - install
      - run-pytest:
          requires:
            - install
      - run-mypy:
          requires:
            - install
